### PR TITLE
Update image.yml

### PR DESCRIPTION
**Pull request by keciad**

### CODE REVIEW

**Comment by BryceLBL** [comment]
Cool.

**Review by michaelbarton — CHANGES_REQUESTED** [review]
Thanks for the pull request Kecia. Could you fork the original bioboxes/jgi-isolate-pipeline repository then create a pull request against that? I think your original fork of that looks good, you'll just need to update the bioboxes version the same way, when the PR is merged into master it should build and push the docker image.

**Comment by michaelbarton** [comment]
@keciad, when you update the jgi isolate pipeline biobox image could you also update the experimental pipeline to use the new merged reads flag for spades? The combination of the merged reads and non merged reads [starts around this line.](https://github.com/bioboxes/jgi-isolate-pipeline/blob/master/image/bin/experimental_pipeline.sh#L106)

```
--merged <file_name> 
    File with merged paired reads.
    If the properties of the library permit, overlapping paired-end reads can be merged using special software.
    Non-empty files with (remaining) unmerged left/right reads (separate or interlaced) must be provided for the same library for SPAdes to correctly detect the original read length.
```

**Comment by michaelbarton** [comment]
If you're interested, you're also welcome to update the spades, unicycler and shovill images too.

**Comment by keciad** [comment]
I update the jgi-isolate-pipeline biobox and did a pull request.

**Comment by michaelbarton** [comment]
@keciad Thanks for updating the jgi isolate pipeline biobox. If you'd like to confirm that it was pushed correctly and update your PR to use that, we can merge it in.

**Comment by keciad** [comment]
I checked the Docker build was sucessfull, and updated my PR to nucleotid.es

**Comment by michaelbarton** [comment]
Thanks Kecia. I merged this in.

**Pull request merged**
