### PR TITLE
Added GATB-Pipeline assembler to image.yml

### PR DESCRIPTION
**Pull request by rchikhi**

### CODE REVIEW

**Comment by michaelbarton** [comment]
Thanks for creating an image for GATB, Rayan. I appreciate you taking the time
to create a container for use in nucleotid.es. I am currently rewriting the
internals of nucleotd.es as much of the initial code was written ad-hoc and
difficult to work with. I anticipate that this should be finished in three
weeks and then I will begin the evaluations again. I'm sorry for this delay. I
look forward to seeing the performance of GATB.

**Comment by rchikhi** [comment]
Hi Michael, Sounds good! Good luck, looking forward to the improved nucleotid.es.

**Comment by michaelbarton** [comment]
@rchikhi I had an error while testing docker-minia. I've pasted the gist online - https://gist.github.com/michaelbarton/a629b4d98602c7d53265

Does this look like a memory error?

**Comment by rchikhi** [comment]
Hi Michael,

It looks like Minia is confused by the input. What's the size of
/inputs/reads.fq.gz , is it one of the nucleotid.es Illumina dataset?
Taking 3 GB of memory during the "Collecting stats" phase is not normal
behavior, never seen this before.

Rayan

**Comment by michaelbarton** [comment]
It's a 200,000 read fastq file, and the gzipped file size is 36Mb. It's the
same set of reads headers as I posted in the other issue if that provides
any further information.

**Comment by rchikhi** [comment]
I've updated docker-minia. I was unable to reproduce the problem using image-builder's test reads.

**Pull request merged**
